urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from .views import (
    ProjectCategoryListView,
    ProjectDetailView,
    ProjectListView,
    ProjectYearArchiveView,
)

app_name = "portfolio"
urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("<int:year>/", ProjectYearArchiveView.as_view(), name="year"),
    path(_("category/"), ProjectCategoryListView.as_view(), name="project_category"),
    path("<slug>/", ProjectDetailView.as_view(), name="project_detail"),
]

models.py
from django.contrib.sites.models import Site
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from filebrowser.fields import FileBrowseField
from project.utils import check_wide_image, generate_unique_slug

from .choices import CATEGORY, COST, STATUS, TYPE


def project_default_intro():
    # following try/except for test to work
    try:
        current_site = Site.objects.get_current()
        return _("Another project by %(name)s!") % {"name": current_site.name}
    except Site.DoesNotExist:
        return _("Another project by this site!")


class Activity(models.Model):
    full = models.CharField(
        max_length=32,
        verbose_name=_("Name"),
    )
    abbrev = models.CharField(
        max_length=4,
        verbose_name=_("Code name"),
    )

    def __str__(self):
        return self.full

    class Meta:
        verbose_name = _("Activity")
        verbose_name_plural = _("Activities")
        ordering = ("abbrev",)


class Project(models.Model):
    slug = models.SlugField(
        _("Slug"),
        max_length=100,
        null=True,
        blank=True,
        help_text=_(
            """
            Appears on the address bar.
            Automatically generated for the active language
            """
        ),
    )
    title = models.CharField(
        _("Title"),
        help_text=_("Title of the project"),
        max_length=50,
        null=True,
        blank=True,
    )
    intro = models.CharField(
        _("Introduction"), default=project_default_intro, max_length=100
    )
    body = models.TextField(_("Text"), null=True)
    date = models.DateField(
        _("Start date"),
        default=now,
    )
    date_end = models.DateField(
        _("End date"),
        null=True,
        blank=True,
    )
    site = models.CharField(
        _("Site"),
        null=True,
        blank=True,
        help_text=_("Loose location"),
        max_length=100,
    )
    client = models.CharField(
        _("Client"),
        null=True,
        blank=True,
        max_length=100,
    )
    category = models.CharField(
        max_length=4,
        choices=CATEGORY,
        default="ALT",
        verbose_name=_("Functional category"),
    )
    type = models.CharField(
        max_length=4,
        choices=TYPE,
        default="ALT",
        verbose_name=_("Type of intervention"),
    )
    status = models.CharField(
        max_length=4,
        choices=STATUS,
        default="ALT",
        verbose_name=_("Status of intervention"),
    )
    cost = models.CharField(
        max_length=4,
        choices=COST,
        default="ALT",
        verbose_name=_("Cost of intervention"),
    )
    activity = models.ManyToManyField(
        Activity,
        blank=True,
        verbose_name=_("Performed activities"),
    )

    def __str__(self):
        return self.title

    def get_full_path(self):
        return reverse("portfolio:project_detail", kwargs={"slug": self.slug})

    def get_activities(self):
        list = []
        for act in self.activity.all():
            list.append(act.full)
        s = ", "
        s = s.join(list)
        return s

    def save(self, *args, **kwargs):
        if not self.title:
            self.title = _("Project-%(date)s") % {
                "date": self.date.strftime("%d-%m-%y")
            }
        if not self.slug:
            self.slug = generate_unique_slug(Project, self.title)
        super(Project, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _("Project")
        verbose_name_plural = _("Projects")
        ordering = ("-date",)


class ProjectCarousel(models.Model):

    home = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="project_carousel",
        verbose_name=_("Project"),
    )
    fb_image = FileBrowseField(
        _("Image"),
        max_length=200,
        extensions=[".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff"],
        directory="images/",
    )
    description = models.CharField(
        _("Description"),
        help_text=_("Will be used in captions"),
        max_length=100,
        null=True,
        blank=True,
    )
    position = models.PositiveSmallIntegerField(_("Position"), null=True)

    class Meta:
        verbose_name = _("Project carousel")
        verbose_name_plural = _("Project carousels")
        ordering = [
            "position",
        ]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        check_wide_image(self.fb_image)

views.py
from django.utils.crypto import get_random_string
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView
from django.views.generic.dates import YearArchiveView

from .choices import CATEGORY, COST, STATUS, TYPE
from .models import Project


class HxPageTemplateMixin:
    def get_template_names(self):
        if not self.request.htmx:
            return [self.template_name.replace("htmx/", "")]
        elif "page" in self.request.GET:
            return ["portfolio/includes/infinite_scroll.html"]
        else:
            return [self.template_name]


class ProjectListView(HxPageTemplateMixin, ListView):
    model = Project
    context_object_name = "progs"
    paginate_by = 6
    template_name = "portfolio/htmx/project_list.html"


class ProjectYearArchiveView(HxPageTemplateMixin, YearArchiveView):
    model = Project
    make_object_list = True
    date_field = "date"
    allow_future = True
    context_object_name = "progs"
    year_format = "%Y"
    allow_empty = True
    template_name = "portfolio/htmx/project_archive_year.html"


class ProjectCategoryListView(HxPageTemplateMixin, ListView):
    model = Project
    context_object_name = "progs"
    template_name = "portfolio/htmx/project_category_list.html"
    paginate_by = 6
    allow_empty = False

    def get_readable(self, list, target):
        for i in list:
            if i[0] == target:
                return i[1]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "category" in self.request.GET:
            readable = self.get_readable(CATEGORY, self.request.GET["category"])
            context["cat_filter"] = _("in Category: %(read)s") % {"read": readable}
        elif "type" in self.request.GET:
            readable = self.get_readable(TYPE, self.request.GET["type"])
            context["cat_filter"] = _("with Intervention type: %(read)s") % {
                "read": readable
            }
        elif "status" in self.request.GET:
            readable = self.get_readable(STATUS, self.request.GET["status"])
            context["cat_filter"] = _("with Status: %(read)s") % {"read": readable}
        elif "cost" in self.request.GET:
            readable = self.get_readable(COST, self.request.GET["cost"])
            context["cat_filter"] = _("with Cost: %(read)s") % {"read": readable}
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        if "category" in self.request.GET:
            qs = qs.filter(category=self.request.GET["category"])
        elif "type" in self.request.GET:
            qs = qs.filter(type=self.request.GET["type"])
        elif "status" in self.request.GET:
            qs = qs.filter(status=self.request.GET["status"])
        elif "cost" in self.request.GET:
            qs = qs.filter(cost=self.request.GET["cost"])
        return qs


class ProjectDetailView(DetailView):
    model = Project
    context_object_name = "prog"
    slug_field = "slug"
    template_name = "portfolio/htmx/project_detail.html"

    def get_template_names(self):
        if not self.request.htmx:
            return [self.template_name.replace("htmx/", "")]
        else:
            return [self.template_name]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # we add the following to feed standardized gallery
        context["main_gal_slug"] = get_random_string(7)
        context["title"] = self.object.title
        # gallery images
        context["images"] = self.object.project_carousel.all()
        return context

templates/portfolio/add_buttons.html
{% load i18n %}
<div class="row">
  <div class="col col-md-6">
    <button class="btn btn-secondary btn-lg btn-block" type="submit">{% translate "Save" %}</button>
  </div>
  <div class="col col-md-6">
    <button class="btn btn-light btn-lg btn-block" type="submit" name="add_another">
      {% translate "Save and add" %}</button>
  </div>
</div>
<small>{% translate "Fields with asterisk (*) are required" %}</small>

templates/portfolio/htmx/project_archive_year.html
{% load i18n %}

{% include 'navbar.html' %}
<main class="flex-shrink-0">
  <div id="content" class="container">
    <div class="card mx-auto" style="max-width: 960px; margin-top: 60px">
      <div class="card-header">
        <div class="row">
          <div class="col">
            <h3>{% translate 'Projects' %} {{ year|date:"Y" }}</h3>
          </div>
          <div class="col text-end">
            {% if perms.portfolio.add_project %}
              <a class="btn btn-secondary" href="/admin/portfolio/project/add/">{% translate "Add project" %}</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="card-body">
        {% include "portfolio/includes/infinite_scroll.html" %}
        <hr class="mb-4">
        <div class="row">
          <div class="col col-6">
            {% if previous_year %}
              <i class="fa fa-arrow-left" aria-hidden="true"></i>
              <a class="link-primary"
                hx-get="{% url 'portfolio:year' year=previous_year.year %}"
                hx-target="#menucont"
                hx-push-url="true">{% translate "PREVIOUS" %}</a>
            {% endif %}
          </div>
          <div class="col col-6 text-end">
            {% if next_year %}
              <a class="link-primary"
                hx-get="{% url 'portfolio:year' year=next_year.year %}"
                hx-target="#menucont"
                hx-push-url="true">{% translate "NEXT" %}</a>
              <i class="fa fa-arrow-right" aria-hidden="true"></i>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% include 'footer.html' %}

templates/portfolio/htmx/project_category_list.html
{% load i18n %}

{% include 'navbar.html' %}
<main class="flex-shrink-0">
  <div id="content" class="container">
    <div class="card mx-auto" style="max-width: 960px; margin-top: 60px">
      <div class="card-header">
        <div class="row">
          <div class="col">
            <h3>{% translate 'Projects' %} {{ cat_filter }}</h3>
          </div>
          <div class="col text-end">
            {% if perms.portfolio.add_project %}
              <a class="btn btn-secondary" href="/admin/portfolio/project/add/">{% translate "Add project" %}</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="card-body">
        {% include "portfolio/includes/infinite_scroll.html" %}
      </div>
    </div>
  </div>
</main>
{% include 'footer.html' %}

templates/portfolio/htmx/project_detail.html
{% load i18n %}

{% include 'pages/gallery.html' %}
<div class="card mx-auto" style="max-width: 960px; margin-top: 60px">
  <div class="card-header">
    <div class="row">
      <div class="col col-6">
        <h3>{{ prog.title }}</h3>
        <p><em>{{ prog.intro }}</em></p>
      </div>
      <div class="col col-6 text-end">
        {% if perms.portfolio.change_project %}
          <a class="btn btn-secondary" href="/admin/portfolio/project/{{ prog.id }}/change/">
            {% translate "Modify" %}
          </a>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col col-6">
        <ul class="list-group list-group-flush">
          {% include 'portfolio/includes/project_meta_large.html' %}
        </ul>
      </div>
      <div class="col col-6">
        <ul class="list-group list-group-flush">
          {% include 'portfolio/includes/project_meta_large_2.html' %}
        </ul>
      </div>
    </div>
    <hr>
    {{ prog.body | safe }}
  </div>
</div>

templates/portfolio/htmx/project_list.html
{% load i18n %}

{% include 'navbar.html' %}
<main class="flex-shrink-0">
  <div id="content" class="container">
    <div class="card mx-auto" style="max-width: 960px; margin-top: 60px">
      <div class="card-header">
        <div class="row">
          <div class="col">
            <h3>{% translate 'Projects' %}</h3>
          </div>
          <div class="col text-end">
            {% if perms.portfolio.add_project %}
              <a class="btn btn-secondary" href="/admin/portfolio/project/add/">{% translate "Add project" %}</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="card-body">
        {% include "portfolio/includes/infinite_scroll.html" %}
      </div>
    </div>
  </div>
</main>
{% include 'footer.html' %}

templates/portfolio/includes/infinite_scroll.html
{% include "portfolio/includes/project_list_loop.html" %}
{% if page_obj.has_next %}
  <p
    hx-get="{% url 'portfolio:project_list' %}?page={{ page_obj.next_page_number }}"
    hx-trigger="revealed"
    hx-swap="afterend">
  </p>
{% endif %}

templates/portfolio/includes/project_list_loop.html
{% load i18n %}
{% load fb_versions %}

{% if progs %}
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for prog in progs %}
      <div class="col">
        <div class="card h-100">
          <div class="card-header">
            <h4 class="link-primary"
              hx-get="{{ prog.get_full_path }}"
              hx-target="#content"
              hx-push-url="true">{{ prog.title }}
            </h4>
          </div>
          <div class="card-body">
            {% if prog.project_carousel.first %}
              <img class="card-img-top"
                src="{% version prog.project_carousel.first.fb_image 'popup' %}"
                alt="{{ prog.intro }}">
            {% endif %}
            <p>
              <em>{{ prog.intro }}</em>
            </p>
            <hr>
            <ul class="list-inline">
              {% include 'portfolio/includes/project_meta.html' %}
            </ul>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% else %}
  <p>{% translate "No projects available" %}</p>
{% endif %}

templates/portfolio/includes/project_meta.html
<li class="list-inline-item">
  <i class="fa fa-calendar-o" aria-hidden="true"></i>
  <a class="link-primary"
    hx-get="{% url 'portfolio:year' year=prog.date.year %}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.date|date:"Y" }}
  </a>
</li>
{% if prog.site %}
  <li class="list-inline-item"><i class="fa fa-map-marker" aria-hidden="true"></i>
    {{ prog.site }}</li>
{% endif %}
<li class="list-inline-item"><i class="fa fa-building" aria-hidden="true"></i>
  <a class="link-primary"
    hx-get="{% url 'portfolio:project_category' %}?category={{ prog.category }}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.get_category_display }}</a>
</li>
<li class="list-inline-item"><i class="fa fa-folder-open" aria-hidden="true"></i>
  <a class="link-primary"
    hx-get="{% url 'portfolio:project_category' %}?type={{ prog.type }}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.get_type_display }}</a>
</li>
<li class="list-inline-item"><i class="fa fa-bar-chart" aria-hidden="true"></i>
  <a class="link-primary"
    hx-get="{% url 'portfolio:project_category' %}?status={{ prog.status }}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.get_status_display }}</a>
</li>
<li class="list-inline-item"><i class="fa fa-euro" aria-hidden="true"></i>
  <a class="link-primary"
    hx-get="{% url 'portfolio:project_category' %}?cost={{ prog.cost }}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.get_cost_display }}</a>
</li>

templates/portfolio/includes/project_meta_large.html
{% load i18n %}

<li class="list-group-item">
  <strong>{% translate "Date" %}:</strong>
  <a class="link-primary"
    hx-get="{% url 'portfolio:year' year=prog.date.year %}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.date|date:"Y" }}
  </a>
  {% if prog.date_end %}
    -
    <a class="link-primary"
      hx-get="{% url 'portfolio:year' year=prog.date_end.year %}"
      hx-target="#menucont"
      hx-push-url="true">
      {{ prog.date_end|date:"Y" }}
    </a>
  {% endif %}
</li>
{% if prog.site %}
  <li class="list-group-item">
    <strong>{% translate "Site" %}:</strong>
    {{ prog.site }}
  </li>
{% endif %}
{% if prog.client %}
  <li class="list-group-item">
    <strong>{% translate "Client" %}:</strong>
    {{ prog.client }}
  </li>
{% endif %}
{% if prog.activity %}
  <li class="list-group-item">
    <strong>{% translate "Activities" %}:</strong>
    {{ prog.get_activities }}
  </li>
{% endif %}

templates/portfolio/includes/project_meta_large_2.html
{% load i18n %}

<li class="list-group-item">
  <strong>{% translate "Category" %}:</strong>
  <a class="link-primary"
    hx-get="{% url 'portfolio:project_category' %}?category={{ prog.category }}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.get_category_display }}</a>
</li>
<li class="list-group-item">
  <strong>{% translate "Type" %}:</strong>
  <a class="link-primary"
    hx-get="{% url 'portfolio:project_category' %}?type={{ prog.type }}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.get_type_display }}</a>
</li>
<li class="list-group-item">
  <strong>{% translate "Status" %}:</strong>
  <a class="link-primary"
    hx-get="{% url 'portfolio:project_category' %}?status={{ prog.status }}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.get_status_display }}</a>
</li>
<li class="list-group-item">
  <strong>{% translate "Cost" %}:</strong>
  <a class="link-primary"
    hx-get="{% url 'portfolio:project_category' %}?cost={{ prog.cost }}"
    hx-target="#menucont"
    hx-push-url="true">
    {{ prog.get_cost_display }}</a>
</li>

templates/portfolio/project_archive_year.html
{% extends 'base.html' %}
{% load i18n %}

{% block head_title %}{% translate 'Projects' %} {{ year|date:"Y" }}{%endblock head_title %}

{% block menucont %}
  {% include 'portfolio/htmx/project_archive_year.html' %}
{% endblock menucont %}

templates/portfolio/project_category_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block head_title %}{% translate 'Projects' %} {{ cat_filter }}{%endblock head_title %}

{% block menucont %}
  {% include 'portfolio/htmx/project_category_list.html' %}
{% endblock menucont %}

templates/portfolio/project_detail.html
{% extends "base_menu.html" %}

{% block head_title %}{{ prog.title }}{% endblock %}

{% block content %}
  {% include "portfolio/htmx/project_detail.html" %}
{% endblock %}

templates/portfolio/project_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block head_title %}{% translate 'Projects' %}{%endblock head_title %}

{% block menucont %}
  {% include 'portfolio/htmx/project_list.html' %}
{% endblock menucont %}